server:
  port: 9999
  tomcat:
    max-threads: 200
    max-connections: 10000
    min-spare-threads: 10
  connection-timeout: 5000
spring:
  application:
    name: my-spring-boot
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useSSL=false&failOverReadOnly=false&maxReconnects=3&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
    hikari:
      auto-commit: true
      connection-timeout: 1000
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
      database: test
      # uri: mongodb://root:123456@localhost:27017/test
#  shardingsphere:
#    datasource:
#      names: ds0, ds1
#      ds0:
#        type: org.apache.commons.dbcp2.BasicDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/ds0?autoReconnect=true&useSSL=false&failOverReadOnly=false&maxReconnects=3&useUnicode=true&characterEncoding=utf8
#        username: root
#        password: 123456
#        hikari:
#          jdbc-url: jdbc:mysql://localhost:3306/ds0?autoReconnect=true&useSSL=false&failOverReadOnly=false&maxReconnects=3&useUnicode=true&characterEncoding=utf8
#          auto-commit: true
#          connection-timeout: 30000
#          idle-timeout: 30000
#          pool-name: ds0
#      ds1:
#        type: org.apache.commons.dbcp2.BasicDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/ds1?autoReconnect=true&useSSL=false&failOverReadOnly=false&maxReconnects=3&useUnicode=true&characterEncoding=utf8
#        username: root
#        password: 123456
#        hikari:
#          jdbc-url: jdbc:mysql://localhost:3306/ds1?autoReconnect=true&useSSL=false&failOverReadOnly=false&maxReconnects=3&useUnicode=true&characterEncoding=utf8
#          auto-commit: true
#          connection-timeout: 30000
#          idle-timeout: 30000
#          pool-name: ds1
#    sharding:
#      default-database-strategy:
#        inline:
#          sharding-column: user_id
#          algorithm-expression: ds$->{user_id % 2}
#      tables:
#        t_order:
#          actual-data-nodes: ds$->{0..1}.t_order$->{0..1}
#          table-strategy:
#            inline:
#              sharding-column: order_id
#              algorithm-expression: t_order$->{order_id % 2}
#        t_order_item:
#          actual-data-nodes: ds$->{0..1}.t_order_item$->{0..1}
#          table-strategy:
#            inline:
#              sharding-column: order_id
#              algorithm-expression: t_order_item$->{order_id % 2}
my:
  aaa: aaa
mybatis:
  type-aliases-package: com.example.boot.entity
  mapper-locations: classpath:mappers/**.xml
  configuration:
    cache-enabled: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
logging:
  config: classpath:config/logback-spring.xml
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
springdoc:
  packages-to-scan: com.example.boot.controller
  paths-to-match: /**
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
